### ISSUE TITLE
Missing module l10n_generic_coa in odoo-spec.yaml

### ISSUE THREAD

**Issue by mourad-ehm** [akretion/docker-odoo-project-prebuild#1]
The module l10n_generic_coa is necessary to test modules based on accounting (ex taxes on sale category modules)
It's not specified in this file ?
https://github.com/akretion/docker-odoo-project-prebuild/blob/12.0/odoo-spec.yaml

@sebastienbeau

**Comment by rvalyi** [comment]
fixed by https://github.com/akretion/docker-odoo-project-prebuild/commit/d8ae0eddce107ed9ef34fdd9d24c0002c0b51893
